server:
  port: 83


spring:
  application:
    name: nacos-order-consumer
  cloud:
    nacos:
      discovery:
        server-addr: 192.168.31.74:80


service-url:
  nacos-user-service: http://nacos-payment-provider
